apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  {{- if eq .Values.global.env_name "dev" }}
  mysqlHost: {{ .Values.mysql.dev.host | b64enc }}
  mysqlPort: {{ .Values.mysql.dev.port | b64enc }}
  mysqlUser: {{ .Values.mysql.dev.user | b64enc }}
  mysqlPassword: {{ .Values.mysql.dev.password | b64enc }}
  mysqlDatabase: {{ .Values.mysql.dev.database | b64enc }}
  mysqlRootPassword: {{ .Values.mysql.dev.rootPassword | b64enc }}
  {{- end }}
  {{- if eq .Values.global.env_name "rc" }}
  mysqlHost: {{ .Values.mysql.rc.host | b64enc }}
  mysqlPort: {{ .Values.mysql.rc.port | b64enc }}
  mysqlUser: {{ .Values.mysql.rc.user | b64enc }}
  mysqlPassword: {{ .Values.mysql.rc.password | b64enc }}
  mysqlDatabase: {{ .Values.mysql.rc.database | b64enc }}
  mysqlRootPassword: {{ .Values.mysql.rc.rootPassword | b64enc }}
  {{- end }}
  {{- if eq .Values.global.env_name "prod" }}
  mysqlHost: {{ .Values.mysql.prod.host | b64enc }}
  mysqlPort: {{ .Values.mysql.prod.port | b64enc }}
  mysqlUser: {{ .Values.mysql.prod.user | b64enc }}
  mysqlPassword: {{ .Values.mysql.prod.password | b64enc }}
  mysqlDatabase: {{ .Values.mysql.prod.database | b64enc }}
  {{- end }}
